// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/sirius.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login   string `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	OpenKey string `protobuf:"bytes,3,opt,name=OpenKey,proto3" json:"OpenKey,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sirius_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sirius_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_proto_sirius_proto_rawDescGZIP(), []int{0}
}

func (x *UserData) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserData) GetOpenKey() string {
	if x != nil {
		return x.OpenKey
	}
	return ""
}

type StatusCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *StatusCode) Reset() {
	*x = StatusCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sirius_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCode) ProtoMessage() {}

func (x *StatusCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sirius_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCode.ProtoReflect.Descriptor instead.
func (*StatusCode) Descriptor() ([]byte, []int) {
	return file_proto_sirius_proto_rawDescGZIP(), []int{1}
}

func (x *StatusCode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MessageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP            string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	CryptoMessage string `protobuf:"bytes,2,opt,name=CryptoMessage,proto3" json:"CryptoMessage,omitempty"`
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sirius_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sirius_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_proto_sirius_proto_rawDescGZIP(), []int{2}
}

func (x *MessageData) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *MessageData) GetCryptoMessage() string {
	if x != nil {
		return x.CryptoMessage
	}
	return ""
}

type UserIPData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP      string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Login   string `protobuf:"bytes,2,opt,name=Login,proto3" json:"Login,omitempty"`
	OpenKey string `protobuf:"bytes,3,opt,name=OpenKey,proto3" json:"OpenKey,omitempty"`
}

func (x *UserIPData) Reset() {
	*x = UserIPData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sirius_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIPData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIPData) ProtoMessage() {}

func (x *UserIPData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sirius_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIPData.ProtoReflect.Descriptor instead.
func (*UserIPData) Descriptor() ([]byte, []int) {
	return file_proto_sirius_proto_rawDescGZIP(), []int{3}
}

func (x *UserIPData) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *UserIPData) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserIPData) GetOpenKey() string {
	if x != nil {
		return x.OpenKey
	}
	return ""
}

var File_proto_sirius_proto protoreflect.FileDescriptor

var file_proto_sirius_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4f, 0x70, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x43,
	0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x24, 0x0a,
	0x0d, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x49, 0x50, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x50, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x70, 0x65, 0x6e, 0x4b, 0x65,
	0x79, 0x32, 0xb2, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3c,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x12, 0x10, 0x2e, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x50, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x06,
	0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x10, 0x2e, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x73, 0x69, 0x72, 0x69, 0x75,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x2e, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x12, 0x2e, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x72, 0x69, 0x75, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sirius_proto_rawDescOnce sync.Once
	file_proto_sirius_proto_rawDescData = file_proto_sirius_proto_rawDesc
)

func file_proto_sirius_proto_rawDescGZIP() []byte {
	file_proto_sirius_proto_rawDescOnce.Do(func() {
		file_proto_sirius_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sirius_proto_rawDescData)
	})
	return file_proto_sirius_proto_rawDescData
}

var file_proto_sirius_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sirius_proto_goTypes = []interface{}{
	(*UserData)(nil),    // 0: sirius.userData
	(*StatusCode)(nil),  // 1: sirius.StatusCode
	(*MessageData)(nil), // 2: sirius.messageData
	(*UserIPData)(nil),  // 3: sirius.userIPData
}
var file_proto_sirius_proto_depIdxs = []int32{
	0, // 0: sirius.Services.GetFriendlyPeers:input_type -> sirius.userData
	0, // 1: sirius.Services.Answer:input_type -> sirius.userData
	0, // 2: sirius.Services.RegisterUser:input_type -> sirius.userData
	3, // 3: sirius.Services.GetFriendlyPeers:output_type -> sirius.userIPData
	1, // 4: sirius.Services.Answer:output_type -> sirius.StatusCode
	1, // 5: sirius.Services.RegisterUser:output_type -> sirius.StatusCode
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sirius_proto_init() }
func file_proto_sirius_proto_init() {
	if File_proto_sirius_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sirius_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sirius_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sirius_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sirius_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIPData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sirius_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sirius_proto_goTypes,
		DependencyIndexes: file_proto_sirius_proto_depIdxs,
		MessageInfos:      file_proto_sirius_proto_msgTypes,
	}.Build()
	File_proto_sirius_proto = out.File
	file_proto_sirius_proto_rawDesc = nil
	file_proto_sirius_proto_goTypes = nil
	file_proto_sirius_proto_depIdxs = nil
}
